monitoredfiles:
  - name: "/etc"
    accesstype:
      - modify
    weight: null
  - name: "/bin"
    accesstype:
      - modify
    weight: null
  - name: "/lib"
    accesstype:
      - modify
    weight: null
  - name: "/boot"
    accesstype:
      - modify
    weight: null
  - name: "/lib64"
    accesstype:
      - modify
    weight: null
  - name: "/var"
    accesstype:
      - modify
    weight: null
  - name: "/opt"
    accesstype:
      - modify
    weight: null
  - name: "/media"
    accesstype:
      - modify
    weight: null
  - name: "/home"
    accesstype:
      - modify
    weight: null
  - name: "/tmp"
    accesstype:
      - modify
    weight: null
  - name: "/root"
    accesstype:
      - modify
    weight: null
monitoredprocessevents:
  - name: "exec"
    weight: high
  - name: "coredump"
    weight: high
  - name: "exit"
    weight: high
  - name: "ptrace"
    weight: high
  - name: "uid"
    weight: high
  - name: "gid"
    weight: high
