/*
 * Deepfence Runtime API v1.5
 *
 * Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider, container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deepfence_runtime_api

type Body1 struct {

	// action to take, when a policy is enforced
	Action string `json:"action,omitempty"`

	// When number of alerts (threshold) is this, policy will be executed
	AlertCountThreshold int32 `json:"alert_count_threshold,omitempty"`

	// Only check in the past 'n' seconds, if ip address reached threshold
	AlertFromTime int32 `json:"alert_from_time,omitempty"`

	// Alert level
	AlertLevel string `json:"alert_level,omitempty"`

	// Number of seconds to block the ip address
	BlockDuration int32 `json:"block_duration,omitempty"`

	// Node type
	NodeType string `json:"node_type,omitempty"`
}
