/*
 * Deepfence Runtime API v1.3
 *
 * Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider, container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deepfence_runtime_api

// Filter policy logs by various fields (key value pairs)
type Deepfencev13usersquarantineProtectionPolicyLogFilters struct {

	// What policy action was performed
	Action []string `json:"action,omitempty"`

	// Policy was executed when number of alerts (threshold) was this
	AlertCountThreshold int32 `json:"alert_count_threshold,omitempty"`

	// Alert id for which the policies got executed
	AlertId []string `json:"alert_id,omitempty"`

	// Host names
	HostName []string `json:"host_name,omitempty"`

	// Node type
	NodeType []string `json:"node_type,omitempty"`

	// Email address of user who created this quarantine protection policy
	PolicyCreatedBy []string `json:"policy_created_by,omitempty"`

	// Severity set in quarantine protection policy
	Severity []string `json:"severity,omitempty"`
}
