/*
 * Deepfence Runtime API v1.5
 *
 * Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider, container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deepfence_runtime_api

// Filter alerts by various fields (key value pairs)
type Deepfencev15alertsFilters struct {

	// Alert ids
	AlertId []string `json:"alert_id,omitempty"`

	// Anomaly types
	Anomaly []string `json:"anomaly,omitempty"`

	// Container image names
	ContainerImage []string `json:"container_image,omitempty"`

	// Container names
	ContainerName []string `json:"container_name,omitempty"`

	// Host names
	HostName []string `json:"host_name,omitempty"`

	// Resource types
	ResourceType []string `json:"resource_type,omitempty"`

	// Alert severity
	Severity []string `json:"severity,omitempty"`
}
