/*
 * Deepfence Runtime API v1.3
 *
 * Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider, container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deepfence_runtime_api

type Options4 struct {

	// The percentage of traffic to capture
	CapturePercentage int32 `json:"capture_percentage,omitempty"`

	// The interface to start packet capture (refer node details api / enumerate api for available interfaces for a node). To start on all interfaces, use 'All'
	InterfaceName string `json:"interface_name,omitempty"`

	// Ports to start packet capture
	PortList []int32 `json:"port_list,omitempty"`

	// Packet header length
	SnapLength int32 `json:"snap_length,omitempty"`
}
