# coding: utf-8

"""
    Deepfence Runtime API v1.5

    Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider, container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.  # noqa: E501

    OpenAPI spec version: 1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import deepfence_runtime_api
from deepfence_runtime_api.api.workload_protection_policy_api import WorkloadProtectionPolicyApi  # noqa: E501
from deepfence_runtime_api.rest import ApiException


class TestWorkloadProtectionPolicyApi(unittest.TestCase):
    """WorkloadProtectionPolicyApi unit test stubs"""

    def setUp(self):
        self.api = deepfence_runtime_api.api.workload_protection_policy_api.WorkloadProtectionPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_workload_protection_policy(self):
        """Test case for add_workload_protection_policy

        Add a node network protection policy.  # noqa: E501
        """
        pass

    def test_bulk_delete_workload_protection_policy(self):
        """Test case for bulk_delete_workload_protection_policy

        Delete multiple node network protection policies  # noqa: E501
        """
        pass

    def test_delete_workload_protection_policy(self):
        """Test case for delete_workload_protection_policy

        Delete a node network protection policy  # noqa: E501
        """
        pass

    def test_get_workload_protection_policy(self):
        """Test case for get_workload_protection_policy

        Get all node network protection policies created by the user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
